//categories
export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_FAILED = "CATEGORIES_FAILED";
export const ADD_CATEGORIES = "ADD_CATEGORIES";

//sub-categories
export const SUB_CATEGORIES_LOADING = "SUB_CATEGORIES_LOADING";
export const SUB_CATEGORIES_FAILED = "SUB_CATEGORIES_FAILED";
export const SUB_CATEGORIES_ADD = "SUB_CATEGORIES_ADD";

//add items to cart
export const ADD_ITEMS_TO_CART = "ADD_ITEMS_TO_CART";
export const ADD_ITEMS_TO_CART_FAILED = "ADD_ITEMS_TO_CART_FAILED";





